# -*- coding: utf-8 -*-
"""superstore analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irCbg2pIE7cUj9dv-2--DL9sGN0qivG4

# ***Analysis of Super Store Dataset***
"""

import numpy as np
import pandas as pd

#import superstore dataset
superstore_df=pd.read_csv(r'/content/SampleSuperstore (1).csv')

superstore_df

superstore_df.head()

superstore_df.shape

superstore_df.columns

superstore_df.info()

superstore_df.isnull().sum()

print(superstore_df['Category'].unique())

print(superstore_df['State'].unique())

no_of_states=superstore_df['State'].nunique()
print("There are %d states in this df."%no_of_states)

print(superstore_df['Sub-Category'].unique())

superstore_df['Segment'].value_counts()

superstore_df.describe()

loss_df=superstore_df[superstore_df['Profit'] < 0]

loss_df

loss_df.describe()

superstore_df.groupby(by='Region').sum()

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(15,3)
plt.bar(loss_df['Sub-Category'],loss_df['Sales']);
plt.rcParams.update({'font.size':10});
plt.xlabel('Sub_Category');
plt.ylabel('Sales');

plt.rcParams['figure.figsize']=(28,8)
plt.bar(superstore_df['Sub-Category'],superstore_df['Sales']);
plt.rcParams.update({'font.size':14});
plt.xlabel('Sub_Category');
plt.ylabel('Sales');
plt.rcParams['figure.figsize']=(28,8)
plt.bar(superstore_df['Sub-Category'],superstore_df['Discount']);
plt.rcParams.update({'font.size':14});
plt.xlabel('Sub_Category');
plt.ylabel('Discount');

plt.rcParams['figure.figsize']=(10,8)
plt.bar(superstore_df['Ship Mode'],superstore_df['Sales']);
plt.rcParams.update({'font.size':14});
plt.xlabel('Ship Mode');
plt.ylabel('Sales');

import seaborn as sns
plt.rcParams['figure.figsize']=(10,5)
sns.countplot(x=superstore_df.Segment)
plt.show();

plt.rcParams['figure.figsize']=(20,5)
plt.rcParams.update({'font.size':12})
sns.countplot(x='Sub-Category',data=superstore_df)
plt.show()

superstore_df.corr()
sns.heatmap(superstore_df.corr(),cmap='Reds',annot=True);
plt.rcParams['figure.figsize']=(10,5)

"""# **Overall Analysis**
The main reason which leads to loss is Discount as if some areas lead to loss due to more discounts, and some areas lead to fewer sales due to fewer discounts, hence it needs to be improved.
It is better to give more discounts during festival seasons, additionally, that will result in more sales.
The Home office segment needs better improvement.
Some cities have fewer sales, lack of awareness can be the reason for this, hence advertising in those cities might help in more sales.

# ***Conclusion***
–> We have learned how to perform Exploratory Data Analysis.

–> We performed it by using the sample superstore dataset.

–>We have seen the loss areas in it and have seen some measures to overcome them.

–> We have seen visualizations and drawn conclusions.
"""